[package]
name = "y2024"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-shared = { path = "../aoc-shared" }
itertools = "0.13"
rayon = "1"
rustc-hash = "2"

[dependencies.regex]
version = "1"
default-features = false
features = ["std", "perf"]
