[package]
name = "y2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-shared = { path = "../aoc-shared" }
itertools = "0.12"
itoa = "1.0.9"
rayon = "1.8.0"
