#!/usr/bin/env bash
set -o pipefail

creds="${XDG_CONFIG_HOME:-"$HOME/.config"}/AoC/session"
[[ ! -f "$creds" ]] && {
    printf 'ERROR: %s\n' "You need to log in first; put session cookie value in: $creds"
    exit 1
}
AoC_session="$(< "$creds")"

case "$#" in
    0)
        echo 'usage: AoC input [year] [date]'
        exit 1
        ;;
    2)
        printf -v Dpadded '%02d' "$2"
        ;;
    3)
        Y="$2"
        printf -v Dpadded '%02d' "$3"
        ;;
esac

[[ -z "$Y" ]] && \
    printf -v Y '%(%Y)T' -1
[[ -z "$Dpadded" ]] && \
    printf -v Dpadded '%(%d)T' -1
D="${Dpadded#0}"
out='/dev/stdout'
case "$1" in
  c*)
      [[ -d challenges ]] && out="challenges/$Dpadded"
      curl "https://adventofcode.com/$Y/day/$D" \
        --fail \
        --cookie session="$AoC_session" \
        --location \
      | lynx -stdin -dump > "$out"
  ;;
  i*)
      if [[ -d input ]]; then
          out="input/$Dpadded"
      elif [[ -d "y${Y}/input" ]]; then
          out="y${Y}/input/$Dpadded"
      fi
      curl "https://adventofcode.com/$Y/day/$D/input" \
        --fail \
        --cookie session="$AoC_session" \
        --location \
      > "$out"
  ;;
  t*)
    [[ -d src/bin ]] && out="src/bin/$Y-$Dpadded.rs"
    cp "${BASH_SOURCE[0]%/*}/../templates/20YY-DD.rs" "$out"
  ;;
esac
